config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      post 'pay/:id'      => 'products#pay', as: 'pay'
      get  'done'         => 'products#done', as: 'done'
     end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  get 'static_pages/index'
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable
  
  attr_writer :last_name, :first_name
  
  before_validation :set_name
  
  
  def last_name
    @last_name || self.name.split(" ").first if self.name.present?
  end
  
  def first_name
    @first_name || self.name.split(" ").last if self.name.present?
  end
  
  def set_name
    self.name = [@last_name, @first_name].join(" ")
  end
         
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
      u.email = auth.info.email
      u.password = Devise.friendly_token[0,20]
      u.name = auth.info.name   # assuming the user model has a name
      u.image = auth.info.image # assuming the user model has an image
    end
    
    # ユーザーはSNSで登録情報を変更するかもしれないので、毎回データベースの情報も更新する
    self.find_or_create_by(provider: provider, uid:uid) do |u|
      u.username   = name
      u.image_path = image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  
  def configure_permitted_parameters
    added_attrs = [:email, :name, :password, :password_confirmation, :last_name, :first_name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'payjp'
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def purchase
  end
  
  def pay
    Payjp.api_key = 'sk_test_fb340a24b07e9f01226ba2d2'
    Payjp::Charge.create(
      amount: 1000,
      card:   params['payjp-token'],
      currency: 'jpy'
    )
    redirect_to action: :done
  end
  
  def done
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :price, :description, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def instagram
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.instagram_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
    

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  
  protected
  
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hayulu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav>
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %> 
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
        ようこそ！ <strong><%= current_user.name %></strong>.
        <%= link_to 'プロフィール変更', edit_user_registration_path %> |
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
      <% else %>
        <%= link_to "サインイン", new_user_registration_path %> |
        <%= link_to "ログイン", new_user_session_path %>
      <% end %>
    </nav>
  </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label '商品名' %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label '価格' %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label '説明' %>
    <%= form.text_area :description, id: :product_description %>
  </div>
  
  <div class="field">
    <%= form.label '画像' %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/done.haml
%p 購入が完了しました！

= link_to '戻る', root_path

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th>説明</th>
      <th>画像</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= image_tag product.image_url(:thumb) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/purchase.haml
= form_tag action: :pay, method: :post do
  :plain
    <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_167982005349b8573cbba36"

app/views/products/show.haml
%p#notice= notice
%p
  %strong 商品名:
  = @product.title
%p
  %strong 価格
  = @product.price
  円
%p
  %strong 説明
  = @product.description
= image_tag @product.image_url.to_s
  
    
  
= form_tag action: :pay, method: :post do
  :plain
    <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_167982005349b8573cbba361"></script>
= link_to 'Edit', edit_product_path(@product)
|
= link_to '一覧に戻る', products_path

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>